default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: "db.mytyutiargnrggzujbwl.supabase.co"
  name: "postgres"
  port: 5432
  user: "postgres"
  password: "XP6oAG7aowQ4CFO4"

  # database_url: "postgresql://postgres:XP6oAG7aowQ4CFO4@db.mytyutiargnrggzujbwl.supabase.co:5432/postgres"

test:
  <<: *default
  database: api_iury_test

production:
  <<: *default
  database_url: <%= ENV["DATABASE_URL"] %>
